### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by mumeranwaar** [jladcr/Moses-for-Mere-Mortals#4]
Hi, 

I am installing MMM on Ubuntu 14.04, and I am following the tutorial.pdf.

I ran into the Segmentation Fault, when I executed ./train-*.

This is how the console looks like:

""
*****\* create binary phrase table
processing ptree for stdin
./train-1.22: line 1024: 27847 Done                    gzip -cfd "$recaserdir/phrase-table.gz"
     27848                       | LC_ALL=C sort
     27849 Segmentation fault      (core dumped) | "$toolsdir/bin/processPhraseTable" -ttable 0 0 - -nscores 5 -out "$recaserdir/phrase-table"
*****\* patch recaser's moses.ini
****************\* Writing training summary
Recaser not correctly trained. Exiting...
""

Please find attached the report with this post.

[!!!INVALID!!!pt-en.C-200000.for_train-60-1.LM-300000.MM-1.Tu-0.day-2016-10-26.time-12-45-21.report.txt](https://github.com/jladcr/Moses-for-Mere-Mortals/files/556421/INVALID.pt-en.C-200000.for_train-60-1.LM-300000.MM-1.Tu-0.day-2016-10-26.time-12-45-21.report.txt)

**Comment by jladcr** [comment]
Hi Mumeranwaar,

Sorry for the late answer. We have sporadically had the same experience that you had with this component that we use but do not author. Whenever that happened, we could solve the problem by re-running the exact same code. I am however assuming that you have enough RAM and disk space.
